services:

  kong:
    image: kong:latest
    container_name: kong-gateway
    user: "root"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
    volumes:
      - ./kong:/usr/local/kong/declarative
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - bank-network
    depends_on:
      - db-cadastro

  servico-cadastro:
    profiles: [ "apps" ]
    build:
      context: ./servico-cadastro
      dockerfile: Dockerfile
    container_name: servico-cadastro
    environment:
      - DB_HOST=db-cadastro
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - KC_ADMIN_USER=${KC_ADMIN_USER}
      - KC_ADMIN_PASS=${KC_ADMIN_PASS}
      - KAFKA_URL=redpanda-estavel:29092
      - KC_URL=http://keycloak-estavel:8080
      - VAULT_URL=http://vault-estavel:8200
      - VAULT_TOKEN=${VAULT_TOKEN}
    networks:
      - bank-network
    depends_on:
      - db-cadastro

  servico-transferencia:
    profiles: [ "apps" ]
    build:
      context: ./servico-transferencia
      dockerfile: Dockerfile
    container_name: servico-transferencia
    environment:
      - DB_HOST=db-transferencia
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - KAFKA_URL=redpanda-estavel:29092
      - KC_URL=http://keycloak-estavel:8080
      - VAULT_URL=http://vault-estavel:8200
      - VAULT_TOKEN=${VAULT_TOKEN}
    networks:
      - bank-network
    depends_on:
      - db-transferencia

  servico-notificacoes:
    profiles: [ "apps" ]
    build:
      context: ./servico-notificacoes
      dockerfile: Dockerfile
    container_name: servico-notificacoes
    environment:
      - DB_HOST=db-notificacoes
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - KAFKA_URL=redpanda-estavel:29092
      - KC_URL=http://keycloak-estavel:8080
      - VAULT_URL=http://vault-estavel:8200
      - VAULT_TOKEN=${VAULT_TOKEN}
    networks:
      - bank-network
    depends_on:
      - db-notificacoes
      - redpanda

  db-cadastro:
    image: postgres:17
    container_name: db-cadastro
    environment:
      - POSTGRES_DB=cadastro_db
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - cadastro_data:/var/lib/postgresql/data
    networks:
      - bank-network

  db-transferencia:
    image: postgres:17
    container_name: db-transferencia
    environment:
      - POSTGRES_DB=transferencia_db
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - transferencia_data:/var/lib/postgresql/data
    networks:
      - bank-network

  db-notificacoes:
    image: postgres:17
    container_name: db-notificacoes
    environment:
      - POSTGRES_DB=notificacao_db
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5435:5432"
    volumes:
      - notificacoes_data:/var/lib/postgresql/data
    networks:
      - bank-network

  db-keycloak:
    image: postgres:17
    container_name: db-keycloak
    environment:
      - POSTGRES_DB=keycloak_db
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5434:5432"
    volumes:
      - keycloack_data:/var/lib/postgresql/data
    networks:
      - bank-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak-estavel
    command: start-dev --db=postgres --db-url=jdbc:postgresql://db-keycloak:5432/keycloak_db --db-username=${DB_USER} --db-password=${DB_PASS}
    depends_on:
      - db-keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASS}
    ports:
      - "8180:8080"
    networks:
      - bank-network

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.2
    container_name: redpanda-estavel
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
    networks:
      - bank-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - bank-network

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    networks:
      - bank-network

  vault-estavel:
    image: hashicorp/vault:latest
    container_name: vault-estavel
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    networks:
      - bank-network
    cap_add:
      - IPC_LOCK

networks:
  bank-network:
    driver: bridge

volumes:
  jenkins_data:
  sonarqube_data:
  cadastro_data:
  transferencia_data:
  keycloack_data:
  notificacoes_data:
