# --- 1. CONFIGURA��ES DE REDE ---
quarkus.http.port=8082
quarkus.devservices.enabled=false

# --- 2. BANCO DE DADOS (CADASTRO_DB - 5432) ---
# --- 2. BANCO DE DADOS ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:5432/cadastro_db
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASS}
quarkus.hibernate-orm.database.generation=none

# ATIVAR o Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.baseline-version=1.0.0

# Configura��es de Teste do Banco
%test.quarkus.hibernate-orm.database.generation=none
%test.quarkus.flyway.migrate-at-start=true
%test.quarkus.scheduler.enabled=false

# --- 3. MENSAGERIA (KAFKA PRODUCER) ---
kafka.bootstrap.servers=${KAFKA_URL:localhost:9092}

mp.messaging.outgoing.pessoa-registrada.connector=smallrye-kafka
mp.messaging.outgoing.pessoa-registrada.topic=v2-pessoa-registrada
mp.messaging.outgoing.pessoa-registrada.value.serializer=org.apache.kafka.common.serialization.StringSerializer
# IMPORTANTE: No ambiente de teste, usamos o conector em mem�ria
%test.mp.messaging.outgoing.pessoa-registrada.connector=smallrye-in-memory

# --- 4. SEGURAN�A (OIDC - VALIDA��O DE TOKENS) ---
quarkus.oidc.auth-server-url=${KC_URL:http://localhost:8180}/realms/bank-realm
quarkus.oidc.client-id=quarkus-app
quarkus.oidc.application-type=service

# --- 5. KEYCLOAK ADMIN (CRIA��O DE USU�RIOS) ---
quarkus.keycloak.admin-client.server-url=${KC_URL:http://localhost:8180}
quarkus.keycloak.admin-client.realm=master
quarkus.keycloak.admin-client.client-id=admin-cli
quarkus.keycloak.admin-client.username=${KC_ADMIN_USER}
quarkus.keycloak.admin-client.password=${KC_ADMIN_PASS}

# --- 8. SEGREDOS (VAULT) ---
quarkus.vault.url=${VAULT_URL:http://localhost:8200}
quarkus.vault.authentication.client-token=${VAULT_TOKEN:}
quarkus.vault.secret-config-kv-path=quarkus-bank

# Configurações para testes passarem sem Crash do Vault
# Configurações para testes passarem sem Crash do Vault na esteira (CI)
%test.quarkus.vault.secret-config-kv-path=
%test.quarkus.vault.url=
%test.quarkus.datasource.username=admin
%test.quarkus.datasource.password=admin

# Fallback das senhas do Keycloak para os testes passarem sem o Vault
%test.quarkus.keycloak.admin-client.username=admin
%test.quarkus.keycloak.admin-client.password=admin

# Propriedade customizada usada no seu PessoaService.java
br.com.bb.cadastro.keycloak.realm=bank-realm

# --- 6. COMUNICA��O ENTRE SERVI�OS (REST CLIENT) ---
br.com.bb.cadastro.client.ContaClient/mp-rest/url=${URL_TRANSF:http://localhost:8083}
br.com.bb.cadastro.client.ContaClient/mp-rest/scope=jakarta.enterprise.context.ApplicationScoped

# --- 7. QUALIDADE E LOGS ---
quarkus.jackson.fail-on-empty-beans=false

quarkus.rest-client.conta-api.url=${URL_TRANSF:http://localhost:8083}/api/contas

# Ativa o JaCoCo no Quarkus
# No seu application.properties
quarkus.jacoco.enabled=true
quarkus.jacoco.report=true
quarkus.jacoco.generate-xml=true
quarkus.jacoco.report-location=jacoco-reports

%test.quarkus.jacoco.enabled=true
%test.quarkus.jacoco.report=true
%test.quarkus.jacoco.generate-xml=true
# Define exatamente onde o relat�rio ser� salvo
%test.quarkus.jacoco.report-location=target/jacoco-reports