pipeline {
    agent any
    tools { maven 'maven' }

    environment {
        SONAR_TOKEN = credentials('sonar-token')
        QUARKUS_DEVSERVICES_ENABLED = 'false'
        // 🚀 Mudamos para 5435 para fugir do conflito com o seu Postgres local
        DB_URL = 'jdbc:postgresql://172.17.0.1:5435/transacoes'
    }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Prepare DB') {
            steps {
                script {
                    // Limpa containers antigos e sobe na porta 5435
                    sh "docker rm -f pg-test || true"
                    sh "docker run -d --name pg-test -e POSTGRES_USER=quarkus -e POSTGRES_PASSWORD=quarkus -e POSTGRES_DB=transacoes -p 5435:5432 postgres:17"
                    sleep 10
                }
            }
        }

        stage('Compilação e Testes') {
            steps {
                dir('servico-transferencia') {
                    // 🚀 Comando em linha única para garantir que o Maven leia TODOS os parâmetros
                    sh "mvn clean verify -Dquarkus.datasource.jdbc.url=${env.DB_URL} -Dquarkus.datasource.username=quarkus -Dquarkus.datasource.password=quarkus -Dquarkus.hibernate-orm.database.generation=drop-and-create -Dquarkus.kafka.devservices.enabled=false"
                }
            }
        }

        stage('Análise SonarQube') {
            steps {
                dir('servico-transferencia') {
                    script {
                        withSonarQubeEnv('SonarQubeServer') {
                            sh "mvn sonar:sonar -Dsonar.projectKey=bb-transferencias"
                        }
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build do Pacote (JAR)') {
            steps {
                dir('servico-transferencia') {
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('servico-transferencia') {
                    sh "docker build -f src/main/docker/Dockerfile.jvm -t bb/servico-transferencia:${env.BRANCH_NAME} ."
                }
            }
        }
    }

    post {
        always {
            sh "docker rm -f pg-test || true"
        }
    }
}