pipeline {
    agent any

    tools {
        maven 'maven'
        // jdk 'java21'
    }

    environment {
        // Credencial criada no Jenkins com o Token do Sonar
        SONAR_TOKEN = credentials('sonar-token')
        TESTCONTAINERS_RYUK_DISABLED = 'true'
        TESTCONTAINERS_HOST_OVERRIDE = 'host.docker.internal'

        QUARKUS_DATASOURCE_DEVSERVICES_TIMEOUT = 'PT5M'
        QUARKUS_KAFKA_DEVSERVICES_TIMEOUT = 'PT5M'
    }

    stages {
        // 1. O Checkout Dinâmico (Usa a branch que disparou o build)
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        // 2. Compilação e Testes (Gera o relatório Jacoco para o Sonar)
        stage('Compilação e Testes') {
            steps {
                dir('servico-transferencia') {
                    // Passamos o timeout diretamente como propriedade do sistema
                    sh "mvn clean verify -Dquarkus.datasource.devservices.timeout=300"
                }
            }
        }

        // 3. Análise SonarQube (Envia os resultados dos testes e cobertura)
        stage('Análise SonarQube') {
            steps {
                dir('servico-transferencia') {
                    script {
                        withSonarQubeEnv('SonarQubeServer') {
                            sh "mvn sonar:sonar \
                                -Dsonar.projectKey=bb-transferencias \
                                -Dsonar.projectName='BB - Microserviço de Transferência' \
                                -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml"
                        }
                    }
                }
            }
        }

        // 4. Quality Gate (O Jenkins espera o veredito do Sonar)
        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    // Aborta se a cobertura for baixa ou houver bugs críticos
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        // 5. Build do Artefato Final (Só chega aqui se a qualidade for 100%)
        stage('Build do Pacote (JAR)') {
            steps {
                dir('servico-transferencia') {
                    sh 'mvn package -DskipTests'
                }
            }
        }

        // 6. Criação da Imagem Docker
        stage('Build Docker Image') {
            steps {
                dir('servico-transferencia') {
                    sh "docker build -f src/main/docker/Dockerfile.jvm -t bb/servico-transferencia:${env.BRANCH_NAME} ."
                }
            }
        }
    }

    post {
        success {
            echo '✅ Build e Análise concluídos com sucesso!'
        }
        failure {
            echo '❌ Falha na pipeline. Verifique os testes ou o Quality Gate no Sonar.'
        }
    }
}