# Geral
quarkus.http.port=8084
quarkus.application.name=servico-notificacoes

# Banco de dados
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASS}

# Vault (Segredos)
quarkus.vault.url=${VAULT_URL:http://localhost:8200}
quarkus.vault.authentication.client-token=${VAULT_TOKEN:}
quarkus.vault.secret-config-kv-path=quarkus-bank

%test.quarkus.vault.authentication.client-token=meu-root-token
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/notificacao_db

quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.baseline-version=1.0.0

# Segurança (OIDC — valida token para o GET de histórico)
quarkus.oidc.auth-server-url=${KC_URL:http://localhost:8180}/realms/bank-realm
quarkus.oidc.client-id=quarkus-app
quarkus.oidc.application-type=service
quarkus.oidc.principal-claim=sub

# Kafka
kafka.bootstrap.servers=${KAFKA_URL:localhost:9092}
mp.messaging.incoming.transacoes-bb.connector=smallrye-kafka
mp.messaging.incoming.transacoes-bb.topic=transacoes-bb
mp.messaging.incoming.transacoes-bb.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.transacoes-bb.failure-strategy=dead-letter-queue
mp.messaging.incoming.transacoes-bb.dead-letter-queue.topic=transacoes-bb-dlq

mp.messaging.incoming.pessoa-registrada.connector=smallrye-kafka
mp.messaging.incoming.pessoa-registrada.topic=v2-pessoa-registrada
mp.messaging.incoming.pessoa-registrada.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.pessoa-registrada.failure-strategy=dead-letter-queue
mp.messaging.incoming.pessoa-registrada.dead-letter-queue.topic=pessoa-registrada-notif-dlq

# Testes
%test.quarkus.oidc.enabled=false
%test.quarkus.flyway.clean-at-start=true
%test.quarkus.flyway.clean-disabled=false
%test.quarkus.hibernate-orm.database.generation=none
%test.mp.messaging.incoming.transacoes-bb.connector=smallrye-in-memory
%test.mp.messaging.incoming.pessoa-registrada.connector=smallrye-in-memory
%test.quarkus.scheduler.enabled=false

# Ativa o JaCoCo no Quarkus
quarkus.jacoco.enabled=true
quarkus.jacoco.report=true
quarkus.jacoco.generate-xml=true
quarkus.jacoco.report-location=jacoco-reports

%test.quarkus.jacoco.enabled=true
%test.quarkus.jacoco.report=true
%test.quarkus.jacoco.generate-xml=true
# Define exatamente onde o relatório será salvo
%test.quarkus.jacoco.report-location=target/jacoco-reports
