CREATE TABLE pessoa (
    id BIGINT NOT NULL,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    keycloakId VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT pk_pessoa PRIMARY KEY (id)
);

CREATE SEQUENCE pessoa_seq START WITH 1 INCREMENT BY 50;